- name: Create an ubuntu instance on Amazon EC2
  hosts: localhost
  vars:
    prefix: nginx-learning
    region: us-east-1
    my_home_ip: "5.18.163.44"

  tasks:
    - name: ssh security group
      ec2_group:
        name: "{{ prefix }}-group"
        description: allow ssh access
        region: "{{ region }}"
        vpc_id: vpc-00b7cafb9452be62d
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 9092
            to_port: 9092
            cidr_ip: "{{ my_home_ip }}/32"
          - proto: tcp
            from_port: 2181
            to_port: 2181
            cidr_ip: "{{ my_home_ip }}/32"
          - proto: tcp
            from_port: 80
            to_port: 80
            cidr_ip: "{{ my_home_ip }}/32"
      register: ec2_group
    - debug: var=ec2_group

    - name: start the instance
      ec2:
        image: ami-02ddb83ff84ca592a
        region: "{{ region }}"
        instance_type: t2.small
        exact_count: 1
        count_tag:
          Name: ansiblebook
        key_name: for-github
        group: ["{{ prefix }}-group"]
        assign_public_ip: yes
        instance_tags: { Name: ansiblebook, type: one, env: test }
        vpc_subnet_id: subnet-056a36446d0695b33
        wait: true
      register: ec2


    - name: Add new instance to host group
      add_host:
        hostname: "{{ item.public_dns_name }}"
        groupname: ec2_launched
      loop: "{{ ec2.tagged_instances }}"

    - name: wait for ssh server to be running
      wait_for: host={{ item.public_dns_name }} port=22 search_regex=OpenSSH
      with_items: "{{ ec2.tagged_instances }}"

- name: install kafka
  hosts: ec2_launched
  gather_facts: False
  tasks:
    - name: "Install java"
      yum:
        name: java-1.8.0-openjdk-devel
        state: present
      become: yes
    - shell: "wget http://nginx.org/packages/centos/7/noarch/RPMS/nginx-release-centos-7-0.el7.ngx.noarch.rpm"
      become: yes
    -









