- name: Create an ubuntu instance on Amazon EC2
  hosts: localhost
  vars:
    prefix: ansible-learning
    region: us-east-1

  tasks:
    - name: ssh security group
      ec2_group:
        name: "{{ prefix }}-group"
        description: allow ssh access
        region: "{{ region }}"
        vpc_id: vpc-00b7cafb9452be62d
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0

    - name: start the instance
      ec2:
        image: ami-00068cd7555f543d5
        region: "{{ region }}"
        instance_type: t3.micro
        exact_count: 1
        count_tag:
          Name: ansiblebook
        key_name: for-github
        group: ["{{ prefix }}-group"]
        assign_public_ip: yes
        instance_tags: { Name: ansiblebook, type: one, env: test }
        vpc_subnet_id: subnet-056a36446d0695b33
        wait: true
      register: ec2

    - debug: var=ec2

    - name: Add new instance to host group
      add_host:
          hostname: "{{ item.public_dns_name }}"
          groupname: ec2_launched
      loop: "{{ ec2.tagged_instances }}"

    - name: wait for ssh server to be running
      wait_for: host={{ item.public_dns_name }} port=22 search_regex=OpenSSH
      with_items: "{{ ec2.tagged_instances }}"

- name: install kafka
  hosts: ec2_launched
  gather_facts: False
  tasks:
    - name: "Install java"
      apt:
        name: openjdk-8

