- name: Create an ubuntu instance on Amazon EC2
  hosts: localhost
  vars:
    prefix: "ansible-learning"
    region: "us-east-1"
    my_home_ip: "5.18.163.44"
    role: "edu-project-ecs-role"
    cluster: "edu-project-cluster"
    task_def: "edu-project-task-def"


    #manual created
    vpc_id: "vpc-00b7cafb9452be62d"
    subnet_id_1: ""
    subnet_id_2: ""

  tasks:
    - name: ssh security group
      ec2_group:
        name: "{{ prefix }}-group"
        description: allow ssh access
        region: "{{ region }}"
        vpc_id: "{{ vpc_id }}"
        rules:
          - proto: tcp
            from_port: 22
            to_port: 22
            cidr_ip: 0.0.0.0/0
          - proto: tcp
            from_port: 9092
            to_port: 9092
            cidr_ip: "{{ my_home_ip }}/32"
          - proto: tcp
            from_port: 2181
            to_port: 2181
            cidr_ip: "{{ my_home_ip }}/32"
      register: ec2_group
    - debug: var=ec2_group


    - name: "Create a role and attach a managed policy called 'PowerUserAccess'"
      iam_role:
        name: "{{ role }}"
        assume_role_policy_document: "{{ lookup('file','policy-ecs-task-def.json') }}"
        region: us-east-1
        managed_policy:
          - arn:aws:iam::aws:policy/CloudWatchFullAccess
          - arn:aws:iam::aws:policy/AmazonEC2FullAccess
          - arn:aws:iam::aws:policy/AWSXrayFullAccess
      register: role
    - debug: var=role


    - name: Create cluster
      # Cluster creation
      ecs_cluster:
        name: "{{ cluster }}"
        region: "{{ region }}"
        state: present

    - name: Create task definition
      ecs_taskdefinition:
        family: "{{ task_def }}"
        region: "{{ region }}"
        containers:
          - name: nginx
            essential: true
            image: "nginx"
            portMappings:
              - containerPort: 8080
                hostPort:      8080
            logConfiguration:
              logDriver: awslogs
              options:
                awslogs-group: /ecs/test-cluster-taskdef
                awslogs-region: "{{ region }}"
                awslogs-stream-prefix: ecs
        launch_type: FARGATE
        cpu: 512
        memory: 1024
        state: present
        network_mode: awsvpc
        execution_role_arn: "{{role.arn}}"
      register: task_def_out
    - debug: var=task_def_out


    - name: Run task
      ecs_task:
        operation: run
        region: "{{ region }}"
        cluster: "{{ cluster }}"
        task_definition: "{{ task_def }}"
        count: 1
        started_by: ansible_user
        network_configuration:
          subnets:
            - subnet-abcd1234
          security_groups:
            - sg-aaaa1111
            - my_security_group
      register: task_output

    - name: Start a task
      ecs_task:
        operation: start
        region: "{{ region }}"
        cluster:  "{{ cluster }}"
        task_definition: "{{ task_def }}"
        task: "{{ task_output.arn }}"
        container_instances:
          - arn:aws:ecs:us-west-2:172139249013:container-instance/79c23f22-876c-438a-bddf-55c98a3538a8
        started_by: ansible_user
        network_configuration:
          subnets:
            - edu-1
            - edu-2
          security_groups:
            - edu-1
            - edu-2
      register: task_output


