- name: Create an ubuntu instance on Amazon EC2
  hosts: localhost
  tasks:
    - name: start the instance
      ec2_instance:
        image: ami-006cda581cf39451b
        region: eu-north-1
        instance_type: t3.micro
        #key_name: mykey
        #group: [web, ssh, outbound]
        #instance_tags: { Name: ansiblebook, type: web, env: production }